# fly.toml file generated for osterbergschmalzle-directus on 2022-12-31T17:23:19-07:00

app = "osterbergschmalzle-directus"

[build]
image = "directus/directus:11"

[env]
DB_CLIENT = "sqlite3"
DB_FILENAME = "/data/data.db"
PORT = "8055"
STORAGE_LOCAL_ROOT = "/data/uploads"
EMAIL_TRANSPORT = "sendgrid"
EMAIL_FROM = "no-reply@cjs.dev"
EMAIL_VERIFY_SETUP = "true"
PUBLIC_URL = "https://admin.osterbergschmalzle.com"

[mounts]
destination = "/data"
source = "osterbergschmalzle_data"

[http_service]
internal_port = 8055
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
